# frozen_string_literal: true

source "https://rubygems.org"

gem "allure-cucumber", "2.16.2"
gem "cucumber", "7.1"
gem "capybara", "3.36"
gem "selenium-webdriver", "4.1"
gem "rspec", "3.11"
gem "faker", "2.20"
gem "mongo", "2.17"
gem "httparty", "0.20.0"
